
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Anushka yadav
 */
public class showdata extends javax.swing.JFrame {

    /**
     * Creates new form showdata
     */
    public showdata() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TABLE1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(null);

        TABLE1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "USERNAME", "PASSWORD", "MEDIA"
            }
        ));
        TABLE1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TABLE1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(TABLE1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 150, 960, 304);

        jLabel1.setText("USERNAME:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 100, 101, 26);
        getContentPane().add(L1);
        L1.setBounds(110, 90, 350, 50);

        jButton1.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jButton1.setText("DECRYPT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(750, 480, 200, 40);

        jButton2.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jButton2.setText("DISPLAY");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(540, 480, 200, 40);

        jButton3.setText("back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(6, 6, 108, 36);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        DefaultTableModel m=(DefaultTableModel)TABLE1.getModel();
L1.setText(""+login_page.u);


try{
Class.forName("java.sql.DriverManager");
Connection c= DriverManager.getConnection("jdbc:mysql://localhost:3306/ayush","root","admin");
Statement  s =  c.createStatement();
String q="select user ,password ,media from mainpass where username='"+login_page.u+"';";

ResultSet rs=s.executeQuery(q);

 

while(rs.next())
{String un=rs. getString("user");
 String pas=rs.getString("password");
 String mk=rs.getString("media");



 m.addRow(new Object[]{un,pas+" (encripted)",mk}); JOptionPane.showMessageDialog(rootPane,"DETAILS OF "+login_page.u);
}


JOptionPane.showMessageDialog(rootPane, "No more record found");
 }



catch(Exception e)
{
    JOptionPane.showMessageDialog(rootPane,e.getMessage());}          // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TABLE1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TABLE1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TABLE1AncestorAdded

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
dispose();
new home_page().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     TABLE1.setModel(new DefaultTableModel(null, new String[]{"USERNAME","PASSWORD","MEDIA"   }));
        DefaultTableModel m=(DefaultTableModel)TABLE1.getModel();
        L1.setText(""+login_page.u); 
try{
    
   
Class.forName("java.sql.DriverManager");
Connection c= DriverManager.getConnection("jdbc:mysql://localhost:3306/ayush","root","admin");
Statement  s =  c.createStatement();
String q="select user ,password ,media from mainpass where username='"+login_page.u+"';";

ResultSet rs=s.executeQuery(q);
int key=6;
     
while(rs.next())
{
    String i="";String j="";
String un=rs. getString("user");String pas=rs.getString("password");String password=pas;
 char [] chars=password.toCharArray();for(char cc: chars){ 
   
     cc-=key; i+=cc;
		   // System.out.print(cc);
		}    j=i;
 String mk=rs.getString("media");

	
 m.addRow(new Object[]{un,j,mk}); JOptionPane.showMessageDialog(rootPane,"DETAILS OF "+login_page.u);
}JOptionPane.showMessageDialog(rootPane, "No More record found");
}
catch(Exception e){ JOptionPane.showMessageDialog(rootPane,e.getMessage());}

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new showdata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JTable TABLE1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
